sudo: required
services: 
  - docker

before_install:
  - docker build -t hercax/docker-react -f Dockerfile.dev . 

script:
  - docker run hercax/docker-react npm run test -- --coverage
  - docker build -t hercax/docker-react-prod .
  - docker run hercax/docker-react-prod

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  name: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-771804787499'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'