sudo: required
services: 
  - docker

before_install:
  - docker build -t hercax/docker-react -f Dockerfile.dev . 

script:
  - docker run hercax/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  name: 'docker-tests'
  env: 'DockerTests-env'
  bucket_name: 'elasticbeanstalk-us-east-1-771804787499'
  bucket_path: 'docker-tests'
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY